twig:
    globals:
        bigfoot_version: '2.2'

bigfoot_core:
    languages:
        back:
            fr:
                value: 'fr'
                date_format: 'dd/MM/yyyy'
            en:
                value: 'en'
                date_format: 'MM/dd/yyyy'

doctrine:
    orm:
        dql:
            numeric_functions:
                acos:    Bigfoot\Bundle\CoreBundle\ORM\Acos
                cos:     Bigfoot\Bundle\CoreBundle\ORM\Cos
                sin:     Bigfoot\Bundle\CoreBundle\ORM\Sin
                radians: Bigfoot\Bundle\CoreBundle\ORM\Radians
            string_functions:
                regexp:          Bigfoot\Bundle\CoreBundle\ORM\Doctrine\Query\MySQL\Regexp
                substring_index: Bigfoot\Bundle\CoreBundle\ORM\Doctrine\Query\MySQL\SubstringIndex
                greatest:        Bigfoot\Bundle\CoreBundle\ORM\Doctrine\Query\MySQL\Greatest
